<a href="https://colab.research.google.com/github/Vishal-3600/100-Days-of-ML/blob/main/100_Days_of_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

.

🔵 **DAY 1 – NumPy (Foundation of ML)**
🎯 Why NumPy?

All ML libraries like:

TensorFlow

PyTorch

scikit-learn

are built on NumPy arrays.

NumPy = Fast matrix operations (C-level speed)

🔹 **1. Creating Arrays**

In [ ]:
import numpy as np

# 1D array
a=np.array([1,2,3,4])

#2D array
b=np.array([[1,2,3,],
          [5,6,7]])# in this 2D you must have same no of elements in its lower dimensions

c = np.array([[[1,2],[3,4]],
              [[5,6],[7,8]]])
print(a)
print(b)
print(c)

[1 2 3 4]
[[1 2 3]
 [5 6 7]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


**2. Important Attributes**

In [ ]:
print(a.shape)# dimensions(meaning: 4 elements and 1 dimensions)
print(b.shape)#(Meaning 2 rows and 3 columns)
print(c.shape)#(meaning 2 block 2 rows and 2 columns) This is 3D array
'''
Layer 1
1 2
3 4

Layer 2
5 6
7 8

'''
print(a.ndim) #number of axes(dimenisons)
print(b.ndim)
print(c.ndim)
print(a.dtype)# dataType

(4,)
(2, 3)
(2, 2, 2)
1
2
3
int64


**3. Vectorized Operations (Very Important)**

In [ ]:
x = np.array([1,2,3])
y = np.array([4,5,6])

print(x + y)      # element-wise addition
print(x * y)      # element-wise multiplication
print()

#2D arrays
x = np.array([[1,2,3],
              [4,5,6]])

y = np.array([[10,20,30],
              [40,50,60]])


print(x + y)
print(x * y) #NumPy still does element-wise operations, but shapes must be compatible.
print()

#3D arrays
x = np.array([[[1,2],[3,4]],
              [[5,6],[7,8]]])

y = np.array([[[1,1],[1,1]],
              [[2,2],[2,2]]])

print(x + y)
print(x * y) #Still element-wise:(Same block(2), Same row(2), Same column(2))

#If shapes don’t match:
x = np.array([1,2,3])
y = np.array([[1,2,3],
              [4,5,6]])

print(x + y)
#This works because of Broadcasting.

#What is Broadcasting?(lean more about it)

#  NumPy automatically expands smaller array to match bigger one.

#x = [1 2 3]
# this becomes
'''[1 2 3]
    [1 2 3]'''

[5 7 9]
[ 4 10 18]

[[11 22 33]
 [44 55 66]]
[[ 10  40  90]
 [160 250 360]]

[[[ 2  3]
  [ 4  5]]

 [[ 7  8]
  [ 9 10]]]
[[[ 1  2]
  [ 3  4]]

 [[10 12]
  [14 16]]]


**🔹 4. Dot Product (Core ML Concept)**

Used in:

Linear Regression    ----> Y=Xw

Neural Networks

SVM

Logistic Regression

In [ ]:
x = np.array([1,2,3])
y = np.array([4,5,6])

dot = np.dot(x, y)
print(dot) #1×4+2×5+3×6=4+10+18=32
print()

#2D × 2D (Matrix Multiplication)

x = np.array([[1,2],
              [3,4]])

y = np.array([[5,6],
              [7,8]])

print(np.dot(x, y))#(Am×n​)⋅(Bn×p​)=(m×p)((2×2) · (2×2) → (2×2))
print()


#2D × 1D
x = np.array([[1,2,3],
              [4,5,6]])   # shape (2,3)

y = np.array([1,1,1])     # shape (3,)
print(np.dot(x, y))

32

[[19 22]
 [43 50]]

[ 6 15]


**5. Matrix Multiplication**

In [ ]:
#(2D × 2D)
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

print(np.matmul(A, B))

#3D × 3D (Batch Matrix Multiplication)
A = np.ones((2, 2, 3))   # shape (batch=2, 2, 3)
B = np.ones((2, 3, 4))   # shape (batch=2, 3, 4)

C = np.matmul(A, B)
print(C.shape)
print()
# Broadcasting in matmul
A = np.ones((2, 2, 3))   # (2,2,3)
B = np.ones((3, 4))      # (3,4) it will be treated as (1,3,4)

C = np.matmul(A, B) #(2,2,3) X (2,3,4) =(2,2,4)
print(C.shape)

# Rules
#Batch → Rows → Columns
#(last-2-dim) × (last-2-dim)
#All other dimensions are treated as batches.

[[19 22]
 [43 50]]
(2, 2, 4)

(2, 2, 4)


**@==Same as matmul()**

In [ ]:
# Mostly used in neural Networks
X = np.ones((32, 100))    # 32 samples
W = np.ones((100, 50))    # 50 neurons

#np.ones() is a NumPy function that creates an array filled entirely with 1s. All values are float by default --> to change into integer--> (np.ones((2,2), dtype=int))
print(np.ones((2,3))) # 2 rows and 3 columns

Y = X @ W
print(Y.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
(32, 50)
